namespace: thothscript

replicaCount: 1

image:
  repository: ghcr.io/jordojordo/thothscript-operator
  pullPolicy: Always
  tag: "0.1.0"

service:
  type: ClusterIP
  port: 3000
  nodePort: null

serviceAccount:
  create: true
  name: thothscript-operator

rbac:
  role:
    resources:
      - name: "pods"
        apiGroup: ""
      - name: "deployments"
        apiGroup: "apps"
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  clusterRole:
    resources:
      - name: "namespaces"
        apiGroup: ""
    verbs: ["get", "list", "watch", "create", "update", "delete"]

env:
  openaiApiSecret: openai-api-key
  openaiApiKey: "<YOUR_OPENAI_API_KEY>"  # Add your OpenAI API Key here