apiVersion: v2
name: daphine
description: An API for streaming music and videos
type: application
home: "https://github.com/jordojordo/daphine"
icon: "https://raw.githubusercontent.com/jordojordo/helm-charts/master/charts/daphine/assets/icon.png"
version: "0.3.0"
appVersion: "0.3.0"
