frontend: "https://example.com" # Required for CORS
nodeName: local-node

deployment:
  labels: 
    yokanga.xyz/api: daphine
  replicaCount: 3
  image:
    repository: "ghcr.io/jordojordo/daphine"
    pullPolicy: IfNotPresent
    tag: 0.2.1
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 50Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2

service:
  type: ClusterIP
  port: 3000

storage:
  useExistingPV: false
  existingPVName: ""
  useExistingPVC: false
  existingPVCName: ""
  pv:
    type: "local" # Default to local. Other option can be 'nfs'
    local:
      name: daphine-pv
      storage: 2Gi
      storageClassName: local-path
      volumeMode: Filesystem
      reclaimPolicy: Retain
      accessModes:
        - ReadWriteOnce
      hostPath: "/mnt/assets"
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values:
                    - local-node
    # nfs:
    #   server: nfs-server.example.com
    #   path: /path/to/nfs
    #   readOnly: false
    #   storage: 2Gi
    #   storageClassName: 'nfs-storage'
    #   accessModes:
    #     - ReadWriteOnce
  pvc:
    name: daphine-pvc
    storageRequest: 2Gi
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce

probes:
  livenessPath: "/health"
  readinessPath: "/ready"
  initialDelaySeconds: 10
  periodSeconds: 30
