apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "thothscript-operator.name" . }}-namespace-manager
rules:
{{- $root := . }}
{{- range $resource := .Values.rbac.clusterRole.resources }}
- apiGroups: [{{ $resource.apiGroup }}]
  resources: [{{ $resource.name }}]
  verbs: {{ toYaml $root.Values.rbac.clusterRole.verbs | nindent 4 }}
{{- end }}
