apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "thothscript-operator.name" . }}-namespace-manager-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "thothscript-operator.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "thothscript-operator.name" . }}-namespace-manager
  apiGroup: rbac.authorization.k8s.io
