apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "thothscript-operator.name" . }}-namespace-manager
rules:
{{- range .Values.rbac.clusterRole.resources }}
- apiGroups: ["{{ .apiGroup }}"]
  resources: ["{{ .name }}"]
  verbs: {{ toYaml $.Values.rbac.clusterRole.verbs | nindent 4 }}
{{- end }}
