apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "thothscript-operator.name" . }}-namespace-manager
rules:
- apiGroups: [""]
  resources: {{ toYaml .Values.rbac.clusterRole.resources | nindent 4 }}
  verbs: {{ toYaml .Values.rbac.clusterRole.verbs | nindent 4 }}
