apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "thothscript-operator.name" . }}-role
  namespace: {{ .Values.namespace }}
rules:
{{- range .Values.rbac.role.resources }}
- apiGroups: ["{{ .apiGroup }}"]
  resources: ["{{ .name }}"]
  verbs: {{ toYaml $.Values.rbac.role.verbs | nindent 4 }}
{{- end }}
