apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.OPENAI_API_KEY_NAME }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.env.OPENAI_API_KEY | b64enc | quote }}
  