apiVersion: v1
kind: Service
metadata:
  name: {{ include "thothscript-operator.name" . }}
  namespace: {{ include "thothscript-operator.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "thothscript-operator.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
