{{- if not .Values.storage.useExistingPVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.storage.pvc.name}}
spec:
  storageClassName: {{.Values.storage.pvc.storageClassName}}
  accessModes: {{toYaml .Values.storage.pvc.accessModes | nindent 4}}
  resources:
    requests:
      storage: {{.Values.storage.pvc.storageRequest}}
{{- end }}