apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    type: {{ .Values.pv.type }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  volumeMode: {{ .Values.pv.volumeMode }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  hostPath:
    # Path of the data within the cluster
    path: {{ .Values.pv.hostPath }}
  nodeAffinity: {{ .Values.pv.nodeAffinity }}
