{{- if not .Values.storage.useExisting.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "daphine.fullname" . }}-pvc
spec:
  storageClassName: {{ .Values.storage.pvc.spec.storageClassName }}
  accessModes:
    {{- toYaml .Values.storage.pvc.spec.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.spec.storageRequest }}
{{- end }}
