apiVersion: v1
kind: Service
metadata:
  name: {{ include "daphine.fullname" . }}
  labels:
    {{- include "daphine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "daphine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
