{{- if and .Values.ingress.enabled .Values.ingress.controller.install -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thothscript-ingress-controller
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: thothscript-ingress
    app.kubernetes.io/part-of: thothscript-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thothscript-ingress
      app.kubernetes.io/part-of: thothscript-ingress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thothscript-ingress
        app.kubernetes.io/part-of: thothscript-ingress
    spec:
      serviceAccountName: thothscript-ingress
      containers:
      - name: controller
        image: k8s.gcr.io/ingress-nginx/controller:v0.47.0
        args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/thothscript-ingress-controller
        - --ingress-class={{ .Values.ingress.controller.className }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: thothscript-ingress-controller
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: thothscript-ingress
    app.kubernetes.io/part-of: thothscript-ingress
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app.kubernetes.io/name: thothscript-ingress
    app.kubernetes.io/part-of: thothscript-ingress
{{- end }}
