apiVersion: v1
kind: Service
metadata:
  name: {{ include "thothscript.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "thothscript.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "thothscript.name" . }}
